version: "3.7"

services:
  bd:
    container_name: bd
    env_file:
      - .env-non-dev
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: app
    ports:
      - "5252:8000"
    depends_on:
      - bd
    restart: always

volumes:
  postgres_data:
